version: '3.8'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"

volumes:
  node_modules: